{{- if .Values.database }}
apiVersion: v1
stringData:
  username: {{ .Values.database.owner }}
  password: {{ .Values.database.password }}
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
type: kubernetes.io/basic-auth
{{- end }}